version: '3'
services:
  buzzer:
    build: 
      dockerfile: ./docker//Dockerfile
      context: ..
    image: tdrimmelen/buzzer:latest
    network_mode: host
    devices:
      - "/dev/snd"
    environment: 
      - "BUZZER_CLOCKURL=http://localhost/shotclock/time"
      - "BUZZER_AUDIOFILE=buzzer/assets/buzzer.wav"
      - "LOGLEVEL=INFO"


